AlmaLinux/albs-frontend

src/components/MockOptionsSelection.vue

This change stabilize mock options form
- Add checks for submit buttons
- Change validation for select fields
- Fixed cleaning buttons
- Some UI improvements

ALBS-45 Stabilize mock options UI

---

src/components/BuildFeedItem.vue
src/components/BuildLogLink.vue
src/components/BuildStatusCircle.vue
src/constants.js
src/pages/Build.vue
src/pages/BuildItemInfo.vue
src/pages/TestLogs.vue
src/router/routes.js

- Add statuses for tests
- Add restart functionality for tests
- Add logs for tests

ALBS-26 Create UI for alts integration

---

src/pages/Build.vue

- Added button "Delete build"
- Added check for delete button

ALBS-52: Added UI for deleting build

---

src/components/BuildFeedItem.vue
src/pages/Build.vue
src/pages/BuildFeed.vue

- add test statuses to the main page
- fix loading statuses to the build page

ALBS-88 Add test statuses to the main page

---

src/components/BuildFeedSearchForm.vue
src/layouts/MainLayout.vue
src/pages/BuildFeed.vue
src/router/routes.js
src/store/modules/builds.js
src/store/modules/users.js

- Added right drawer for search filters
- Added search button

ALBS-24: Added UI for searching builds

---

src/layouts/MainLayout.vue
src/pages/BuildFeed.vue

- Remove the top strip
- Lock scrolling of the search area

UI improvements

---

src/pages/Build.vue

Divide src.rpm from binary rpms

ALBS-47 Divide src.rpm from binary rpms

---

src/pages/Build.vue

Add secure boot label to the build page

ALBS-140 Add secure boot label to the build page

---

src/components/BuildSelectionForm.vue
src/components/PackageLocationSelectionForm.vue
src/components/ReleaseView.vue
src/constants.js
src/layouts/MainLayout.vue
src/pages/CreateRelease.vue
src/pages/ReleaseFeed.vue
src/router/routes.js

New build system release form
- Builds/Projects selection form
- Package location selection form
- Release feed

ALBS-137 New build sys release form

---

src/components/LogView.vue
src/constants.js
src/pages/BuildItemInfo.vue
src/pages/BuildLogs.vue
src/pages/TestLogs.vue

Add summary table for test results

ALBS-99 Add summary table for test results

---

src/components/PackageLocationSelectionForm.vue

Fix ppc64le release packages

---

src/pages/ReleaseFeed.vue

Fix incorrect version-release view in Release Feed UI

ALBS-214 Fix incorrect version-release view in Release Feed UI

---

src/components/ModuleEditor.vue
src/components/ProjectSelectionWindow.vue
src/components/ProjectSelector.vue
src/pages/BuildPlanner.vue

- Moving checkbox into ProjectSelector
- Added showing not updated module packages

ALBS-194: Changed UI for showing not updated module packages

---

src/components/BuildFeedItem.vue
src/pages/Build.vue

We need to expose information about built modules for the build.

ALBS-289 Add information about built modules

---

src/components/BuildSelectionForm.vue
src/components/PackageLocationSelectionForm.vue
src/components/ReleaseView.vue
src/pages/Build.vue

We want to see if package isn’t notarized in package location screen (we can use same icon as for builds/artifacts), also we want to have ability to release not notarized packages, add one more flag for this ability

ALBS-484 Add CodeNotary release integration

---

src/pages/Build.vue
src/pages/BuildFeed.vue

Show release status of a build on the Build Feed and on the Build Page

ALBS-569 Show release status

---

src/components/PackageLocationSelectionForm.vue

Release UI become messi when trying to release notarized and non-notarized build

ALBS-598 Fix messy Release UI

---

src/components/ReleaseView.vue

We have a lot of free space around the table that can be used for a table

ALBS-621 Fix table width on the release view page

---

src/pages/DocumentationViewer.vue
src/pages/ProductFeed.vue

- Change color of table to white like in other tables
- Remove created by section
- Add username to products name
- Add shadows
- Add watcher to search input
- Add loader on the Documentation page
- Change code font in documentation

ALBS-627 Impove products UI

---

src/components/PackageLocationSelectionForm.vue
src/components/ReleaseView.vue
src/pages/Build.vue
src/pages/ReleaseDetails.vue
src/pages/ReleaseFeed.vue
src/router/routes.js
src/store/modules/release.js

- Added detail page for releases
- Add open release from build page
- Added search form for releases by platform/product/status
- Add showing created date on the release feed
- Add showing product on the release feed
- Add warning to the release feed If we have WARNING: in release logs

ALBS-630 Minor improvements for releases

---

src/components/SlideTransition.vue
src/components/UserRolesEditor.vue
src/layouts/MainLayout.vue
src/pages/AdminUsers.vue
src/pages/Github.vue
src/router/routes.js
src/store/index.js
src/store/modules/users.js
src/utils.js

Depends on https://github.com/AlmaLinux/albs-web-server/pull/289

ALBS-449: Implement Admin pages

---

quasar.conf.js
src/components/BuildRef.vue
src/components/MockOptionsSelection.vue
src/components/MockOptionsShow.vue
src/components/ModuleEditor.vue
src/components/ProjectSelectionWindow.vue
src/components/ProjectSelector.vue
src/pages/Build.vue
src/pages/BuildPlanner.vue

BS only allows to ADD modules but not remove modules that come from modulemd.src.txt. Also BS automatically enable module we’re going to build and does not allow to disable it.

ALBS-324 Enabled modules for module build should be fully configurable in UI

---

src/pages/ErrataFeed.vue
src/router/routes.js

Now we cannot send or go to a specific Errata. It is necessary to add id to the URL when selecting an Errata

ALBS-741 Add id to the Errata info URL

---

src/pages/Build.vue

Sign log looks awful, needs to increase dialog width, change font and background color

ALBS-750 Increase sign log width

---

src/components/BuildSelectionForm.vue

‘New Release’ not opening in Safari because we use lookbehind regexp, but [it is does not support in Safari ](https://caniuse.com/js-regexp-lookbehind)

ALBS-775 Fix 'New Release' not opening in Safari

---

src/pages/TestLogs.vue

Related PR: https://github.com/AlmaLinux/alts/pull/37

ALBS-842 Add uninstall test

---

src/components/BuildFeedItem.vue
src/components/EssentialLink.vue
src/components/ProjectSelectionWindow.vue
src/components/ProjectSelector.vue
src/layouts/MainLayout.vue
src/pages/Build.vue
src/pages/BuildFeed.vue
src/pages/BuildPlanner.vue
src/pages/TeamFeed.vue
src/pages/TeamInfo.vue
src/utils.js

Hi all, just added some IDs for testing purposes. Please tell me if something looks bad.

Add ids for automation scripts

---

src/components/ProjectSelectionWindow.vue

https://github.com/AlmaLinux/build-system/issues/34

Fix project is being added as 'undefined'

---

src/components/PackageLocationSelectionForm.vue
src/constants.js

Hi guys,
I just added new trustness tooltips. You can see screenshots on the task: https://cloudlinux.atlassian.net/browse/ALBS-656 
Thanks,
Have a nice day.

ALBS-656: Trustness tooltip

---

src/layouts/MainLayout.vue
src/pages/ProductFeed.vue
src/pages/TeamFeed.vue
src/pages/TestRepositoryConfigurator.vue
src/pages/TestRepositoryFeed.vue
src/router/routes.js
src/store/index.js
src/store/modules/test_repositories.js
src/utils.js

related: https://github.com/AlmaLinux/albs-web-server/pull/621

Create UI for test repositories

---

src/pages/TestLogs.vue

Add new section to display system information logs. Related: https://cloudlinux.atlassian.net/browse/ALBS-1169

Add 'system_info' section in test logs layout

---

Dockerfile

Related to https://github.com/AlmaLinux/build-system/issues/131

Container now runs as albs:albs (1000:1000) user

---

src/components/ErrataInfo.vue

- Add a button for rematching errata packages
- prettier syntax

Fixes AlmaLinux/build-system#147

---

src/App.vue
src/components/ErrataInfo.vue
src/layouts/MainLayout.vue
src/pages/ProductDetails.vue
src/router/routes.js

Resolves: AlmaLinux/build-system#103

Open Security Advisories & COPR list

---

src/pages/Build.vue

Resolves: AlmaLinux/build-system#169

Fix "Restart build tests" functionality 

---

src/components/BuildSelectionForm.vue

Fixes: AlmaLinux/build-system#170

Fix product search in the New Release Page

---

.github/workflows/prettier.yaml
.github/workflows/test.yaml

Resolves: AlmaLinux/build-system#181

Bump github actions dependencies

---

src/constants.js
src/pages/Build.vue
src/pages/BuildFeed.vue
src/utils.js

Resolves: https://github.com/AlmaLinux/build-system/issues/81

Add support to cancel testing

---

src/components/ErrataInfo.vue
src/pages/ErrataFeed.vue

Resolves: https://github.com/AlmaLinux/build-system/issues/197

Make use of platform_id when interacting with errata API endpoints

---

src/components/ErrataInfo.vue

Resolves: https://github.com/AlmaLinux/build-system/issues/197

Add platform_id when calling errata/update_package_status endpoint

---

src/components/BuildFeedItem.vue
src/pages/Build.vue

Related to https://github.com/AlmaLinux/build-system/issues/127
Resolves: https://github.com/AlmaLinux/build-system/issues/151
Goes well with https://github.com/AlmaLinux/albs-web-server/tree/AlmaLinux/build-system-127-build-new-modularity

Update modular info display after pulp migration

---

src/components/ErrataInfo.vue

Resolves: https://github.com/AlmaLinux/build-system/issues/250
Backend: https://github.com/AlmaLinux/albs-web-server/pull/858

Enable scrollbar for failed errata release list of packages

---

src/components/BuildFeedItem.vue
src/pages/Build.vue
src/pages/BuildItemInfo.vue
src/pages/BuildLogs.vue
src/utils.js

Resolves: AlmaLinux/build-system#212

Change build order

---

src/components/ErrataInfo.vue
src/pages/TestRepositoryFeed.vue

Resolves: https://github.com/AlmaLinux/build-system/issues/105
-Added dropdown menue to select team when creating Test Repo
-In conjunction with https://github.com/AlmaLinux/albs-web-server/pull/881

RBAC for Test Repositories - Frontend - Issue 105

---

src/components/ModuleEditor.vue

Resolves: https://github.com/AlmaLinux/build-system/issues/247

Add the ability to disable the build package

---

src/pages/ErrataFeed.vue

Resolves: https://github.com/AlmaLinux/build-system/issues/308
**The fontend part of this task needs to be discussed**
- Added an ability to choose an issued_date of erratas
Backend: https://github.com/AlmaLinux/albs-web-server/pull/929

Create endpoint to reset package mappings of unreleased erratas

---

src/components/UserRolesEditor.vue

Fixes: AlmaLinux/build-system#334

Fix can't modify user's roles in a team UI

---

src/components/ErrataInfo.vue
src/components/ErrataReferencesSelection.vue
src/constants.js
src/pages/CreateErrata.vue
src/pages/ErrataFeed.vue
src/router/routes.js
src/utils.js

Resolves: AlmaLinux/build-system#301

Implement a UI to create new security advisories

---

src/components/ErrataInfo.vue

Resolves: https://github.com/AlmaLinux/build-system/issues/352
**DO NOT MERGE** until the new errata workflow is merged into master.

Show noarch packages in the list of errata packages

---

src/components/ErrataInfo.vue

Depends on https://github.com/AlmaLinux/albs-web-server/pull/998
Resolves: https://github.com/AlmaLinux/build-system/issues/351
**DO NOT MERGE** until new errata workflow is merged and deployed

Use the new errata release endpoint

---

src/pages/ProductDetails.vue
src/router/routes.js

Resolves: AlmaLinux/build-system#359

Adding platforms to products to UI

---

src/components/ErrataInfo.vue

Resolves: AlmaLinux/build-system#388

Fix Save button for Errata Info page

---

src/pages/ErrataFeed.vue

Resolves: AlmaLinux/build-system#325

Add bulk releases to Errata Feed

---

src/pages/BuildLogs.vue

Fixes: AlmaLinux/build-system#390

Fix srpm mock logs in UI

---

src/pages/CreateErrata.vue

Goes well with https://github.com/AlmaLinux/albs-web-server/pull/1082
Fixes: https://github.com/javihernandez/albs-web-server/pull/new/bs-395

Take packages nevra from build meta field

---

src/components/ErrataReferencesSelection.vue
src/constants.js
src/pages/CreateErrata.vue

Resolves: https://github.com/AlmaLinux/build-system/issues/393

Updates to the errata creation UI and process

---

src/pages/CreateErrata.vue

Resolves: https://github.com/AlmaLinux/build-system/issues/377
Plays nice with https://github.com/AlmaLinux/albs-web-server/pull/1093

Send devel module in errata creation payload

---

src/components/ErrataInfo.vue
src/pages/ErrataFeed.vue

Fixes: AlmaLinux/build-system#419

Fix Reset matched packages do not work on advisory with the same ID

---

src/components/ProjectSelector.vue
src/pages/BuildPlanner.vue

Resolves: https://github.com/AlmaLinux/build-system/issues/484
Depends on https://github.com/AlmaLinux/albs-web-server/pull/1155

Take modularity versions from platform.data
