AlmaLinux/albs-frontend

- src/components/BuildRef.vue
- src/components/ProjectSelectionWindow.vue
- src/constants.js
- src/utils.js
- Changed `BuildRef` component for showing build tasks refs
- Added `utils` script with functions for build tasks refs
- Added `BuildTaskRefType` enum for build tasks refs
- Added few fixes for showing build tasks refs
> ALBS-67: Added refs in build tasks

- src/layouts/MainLayout.vue
- src/pages/Build.vue
- src/pages/BuildFeed.vue
- src/pages/BuildPlanner.vue
- Add a little bit empty space on top of build feed
- Change linked builds under build to look like link, and not like text
- Decrease Mock options font size under build
- Remove automatic appearance of the build search drawer
- Add ability to open linked builds in a new tab
> ALBS-50 Font/color improvements

- src/pages/CreateRelease.vue
If create/update release will fall, we doesn’t see error and package location screen still show loading, that’s incorrect
> ALBS-373 Add error during create/update release

- src/components/PackageLocationSelectionForm.vue
Right now if we release packages for AlmaLinux 9, we can’t release in s390x repos, because this arch is missing
Need to add s390x arch for AlmaLinux 9 or generate arch columns in package location screen by arch_list from platform for every platform that we release
> ALBS-397 Add s390x arch for package location screen

- src/layouts/MainLayout.vue
Issue description: If I opened a few tabs (add new release or something like this) before logout.
I was able to release some package when I had logged out in another tab.
The tab was opened before logout.
> ALBS-429 Remove access to the functional after logout

- src/components/BuildFeedItem.vue
- src/components/PackageLocationSelectionForm.vue
- src/pages/Build.vue
- src/utils.js
Release preview allows to choose repo for every package.
The same should be done for module metadata. Under packages should be form with modules (if they are in release).
NAME:STREAM:VERSION:CONTEXT and repo to release. By default repo should be chosen automatically by Beholder, but it’s important to see and change what will be released and where.
> ALBS-220 Add modules to release preview with ability to choose repo

- src/components/ReleaseView.vue
The release info dialog stops working if the release doesn't contain any log
> ALBS-470 Fix release info dialog

- src/pages/BuildLogs.vue
Currently, build logs are not sorted by any value, so finding the right log can be difficult
> ALBS-499 Sort build logs by name and timestamp

- src/components/ProjectSelector.vue
When you add more than one project with the same name and then delete one of them, then all projects with that name will be deleted
> ALBS-506 Fix deleting projects in build planner

- src/components/ReleaseView.vue
Need to sort repositories by name, and add the ability for the user to manually sort the repositories by the arch and is_debug fields
> ALBS-665 Sort repositories on the Release Details page

- quasar.conf.js
- src/pages/BuildPlanner.vue
Add warning saying build product, platform, and architecture are required to create a new build. Currently, when creating a new build it allows a user to proceed with adding a project after adding a product and a platform. 
Existing behavior: when adding a platform, there will appear a “blue pencil” saying you can proceed, but you cant. when also choosing a product, you’ll be able to proceed and add projects. Though, the build won’t be created as no architectures were selected. There’s no warning about that.
Expected behavior: a “blue pencil” sign should appear only after choosing a product, a platform and architecture/s. If one of them wasn’t selected, there should be a warning for that.
> ALBS-634 Add warnings when creating a new build

- src/components/PackageLocationSelectionForm.vue
- src/pages/ReleaseFeed.vue
Current we show src packages in the Packages column, but if we don't have a src package in a release, we show all of the release's packages, which makes the Release Feed page look very bulky. And if we have more than one src we show all of them, causing duplicates.
> ALBS-667 Show only projects on the Release Feed

- src/pages/Build.vue
In case the API is running slow and requesting the build from the API takes more than a minute, we shouldn't reload until the first request is finished (successfully or not).
> ALBS-753: Do not wait until build request is done to set reload to false

- src/pages/Github.vue
In the new version of fastapi-users filed "user_id" changed to "sub"
Links https://github.com/AlmaLinux/albs-web-server/pull/400
> ALBS-891 Fix parsing user id in jwt token

- src/pages/BuildLogs.vue
Now logs include the build id, see https://github.com/AlmaLinux/albs-node/commit/a9e648e832267d764fd7f3e70b3c214146798ee5
Can check the two updated regex here:
* binary: https://regexr.com/7abls
* srpm: https://regexr.com/7ablp
This way we ensure we pick up old and new build log names.
> ALBS-1041: Updated mock binary build logs regex

- src/pages/Build.vue
This fixes the issue where non modular builds are not properly rendered due to a wrong rpm_modules check.
Fixes: https://github.com/AlmaLinux/build-system/issues/151
> Update rpm_modules check in build pages

- Dockerfile
- README.md
- Switch to Almalinux 9
- Use `npm ci` to install dependencies from `package-lock.json`
- Store `node_modules` in the image (in `/home/albs`)
Resolves: AlmaLinux/build-system/issues/223
> Refactoring of Dockerfile

- src/components/ErrataInfo.vue
- src/pages/ErrataRelease.vue
- src/router/routes.js
`ErrataRelease` page now takes data in the query to later on be passed on to `releases/new` endpoint.
Fixes: https://github.com/AlmaLinux/build-system/issues/380
> Fix release packages button in errata interface

- src/components/ErrataReferencesSelection.vue
- src/constants.js
- src/pages/CreateErrata.vue
After having fixed the problems when creating new erratas in backend, I also had to fix the erratas ReferenceType handling in UI to make backend actually successfully process the new errata.
Resolves: https://github.com/AlmaLinux/build-system/issues/364
> Fix errata ReferenceType handling

- src/pages/CreateErrata.vue
Fixes: https://github.com/AlmaLinux/build-system/issues/378
Fixes: https://github.com/AlmaLinux/build-system/issues/415
This is the frontend side of https://github.com/AlmaLinux/albs-web-server/pull/1115
> Send build_id in errata packages when creating erratas
